### ISSUE TITLE
Feature Requests: append speaker to existing group 

### ISSUE THREAD

**Issue by blackmore190** [B5r1oJ0A9G/teufel_raumfeld#25]
I'd Like  the possibility to add(and also drop) speakers to existing zones without complete recreation of the group

**Comment by B5r1oJ0A9G** [comment]
It's implemented in current ``master`` branch. See: https://github.com/B5r1oJ0A9G/teufel_raumfeld/wiki#services

**Comment by B5r1oJ0A9G** [comment]
Released in  [v0.1.13-alpha1](https://github.com/B5r1oJ0A9G/teufel_raumfeld/releases/tag/v0.1.13-alpha1).
