### ISSUE TITLE
Set the volume of a specific room regardless of its zone

### ISSUE THREAD

**Issue by THaeckel** [B5r1oJ0A9G/teufel_raumfeld#27]
Hi,
is it possible to adjust, increase or decrease the volume of a particular room/speaker regardless of the zone it is in?
From my testing, it looks like you can only decrease/increase the volume of a media player, which represents a complete zone. It is also possible to set the volume for a specific room in an active zone. However, in my automations I don't know which zone is currently active and just want to set the volume of a specific room. Is there a way to achieve this? 
Best regards,
Timo

**Comment by B5r1oJ0A9G** [comment]
Hi,

This is not possible right now

One could perhaps work around it by letting Home Assistant know about each expected Zone configuration and check these about the one that is enabled and set the volume for the room in the enabled one. Another option could be to iterate over all zones and set the volume for the concerned room in each of them. However, I have not tested this yet.

It could be implemented in `teufel_raumfeld` by a new service. The service would find the active zone with the concerned room(s) and set the volumen for the room in that zone.

**Comment by THaeckel** [comment]
Thanks for the fast reply. 
The work around of listing possible groups containing this room you suggested at least works for the play function so I would assume one can get it running for set absolute volume as well. I will look into this and also check out the idea of adding a new service.

**Comment by B5r1oJ0A9G** [comment]
It's implemented in current ``master`` release. See: https://github.com/B5r1oJ0A9G/teufel_raumfeld/wiki#services

**Comment by B5r1oJ0A9G** [comment]
Released in  [v0.1.13-alpha1](https://github.com/B5r1oJ0A9G/teufel_raumfeld/releases/tag/v0.1.13-alpha1).
