### ISSUE TITLE
Issues with Repo and Integration since 2022.02

### ISSUE THREAD

**Issue by feutl** [B5r1oJ0A9G/teufel_raumfeld#28]
I had the integration disabled for a long time, just because I had no time to get it working properly.
Now with the new media integration in 2022.02 I thought it is a good idea to start with.

Enabled the integration, the speakers popped up but they were not usable, nor the media card, the custom mini media card or the new HA media had the option to choose them.

After deleting the integration from HA and HACS, I started over again and now I am unable to install the latest release, the log says

```
This error originated from a custom integration.

Logger: custom_components.hacs
Source: custom_components/hacs/repositories/base.py:867
Integration: HACS (documentation, issues)
First occurred: 8:23:13 AM (2 occurrences)
Last logged: 8:23:47 AM

No assets found for release 'tags/v0.1.10-alpha1'
```

v0.1.10-alpha is still able to be downloaded and works, but HACS bugs me with messages to update to the "latest alpha1" version.

**Comment by B5r1oJ0A9G** [comment]
So far everything is still working on my instance. Therefore I created an instance from scratch and the integration works as expected.

Can you please describe your setup in more detail?

**Comment by feutl** [comment]
Today I had some time testing around, also installed the latest HACS (1.23.0), which worked.
After a reboot of the system I gave the Raumfeld Integration another try to update, but after a reboot it is still telling me that the alpha1 is available and I need to update. 

I am running HA on a Raspberry Pi 4 with the image provided by HA.
If you could point me to the information you are curious about, I can provide it to you.

**Comment by B5r1oJ0A9G** [comment]
I am glad to hear that and many thanks for the feedback!
