### ISSUE TITLE
Hass 2022.4.0 not loaded and can't remove/readd

### ISSUE THREAD

**Issue by eladore** [B5r1oJ0A9G/teufel_raumfeld#31]
As title. With the newest hass which is pretty amazing, the integration won't work any more. I can't even uninstall it in HACS or remove is in the integration page. When I delete it there. Nothing happens... 

With "ignore"  you can deletetr it in in hacs, reboot and delete it from the integrations. But then after reinstalling in hacs yout can't add a integration as it saye error this integration does not support configuration with gui....

**Comment by btittelbach** [comment]
This is the corresponding Homeassistant error from the log:
`
Logger: homeassistant.setup
Source: setup.py:162
First occurred: 3:23:52 AM (1 occurrences)
Last logged: 3:23:52 AM

Setup failed for custom integration teufel_raumfeld: Unable to import component: cannot import name 'UpnpFactory' from 'async_upnp_client' (/usr/local/lib/python3.9/site-packages/async_upnp_client/__init__.py)

`

**Comment by wunni1** [comment]
the same with HASS 2022.4.1

**Comment by RamonM77** [comment]
I'm under the impression this project isn't alive anymore, unfortunately.

I had the same issue, the integration wasn't working anymore and I couldn't remove it as well. However, you can do this manually.
In your editor, open "/config/.storage/core.config_entries" and delete the "teufel_raumfeld" section (the part between { and }). Restart HA and now you can remove the repo from HACS.

**Comment by blackmore190** [comment]
The behavior is the same for me. After I restored Core from the backup, everything worked again. So it's really because of the update.

**Comment by btittelbach** [comment]
I've created two pull requests based on the fix in OpenHome mentioned above.

https://github.com/B5r1oJ0A9G/teufel_raumfeld/pull/32
https://github.com/B5r1oJ0A9G/hassfeld/pull/6

I hope they fix the issue or at least help the maintainer to fix the issue faster.
