### ISSUE TITLE
Media player does not support browsing media

### ISSUE THREAD

**Issue by kalbfuss** [B5r1oJ0A9G/teufel_raumfeld#33]
Since the latest upgrade to v0.1.12-alpha4 I receive the following error message, when using the "Play media" service:
"Media player does not support browsing media".
I am running HA version 2022.4.7. This used to work before.

**Comment by kalbfuss** [comment]
Working again. In the meanwhile I am running Teufel Raumfeld v0.1.12-alpha4 on Home Assistant version 2022.8.7. Issue can probably be closed.

**Comment by B5r1oJ0A9G** [comment]
Thanks for the feedback! Closing it as suggested.
