### ISSUE TITLE
Wiki Typos and future improvements / contributions process?

### ISSUE THREAD

**Issue by feutl** [B5r1oJ0A9G/teufel_raumfeld#35]
I found some Wiki Typos and being unable to edit them.
I also would help contributing to the wiki to make this add-on more accessible for others who struggle too (like me https://github.com/B5r1oJ0A9G/teufel_raumfeld/discussions/10#discussioncomment-2861235)

![image](https://user-images.githubusercontent.com/8522012/171342639-d3bea271-2d7f-487c-9db0-c3256d11cf50.png)

![image](https://user-images.githubusercontent.com/8522012/171342659-47a7779b-2fe5-4746-8fd3-fa164962e1b5.png)

Just let me know how I can help with this.

**Comment by B5r1oJ0A9G** [comment]
Thanks a lot!
The typos are fixed now. By the way, you can also consider to create pull requests for fixes of Wiki pages.
Best,
Marc
