### ISSUE TITLE
Invalid host

### ISSUE THREAD

**Issue by Ivanverdonck** [B5r1oJ0A9G/teufel_raumfeld#8]
Hi,

After installing teufel_raumfeld (using HACS), the integration works perfectly, but after a restart of homeassistant i get following error:
```
Logger: custom_components.teufel_raumfeld
Source: custom_components/teufel_raumfeld/__init__.py:105
Integration: Teufel Raumfeld (documentation, issues)
First occurred: 13:43:05 (1 occurrences)
Last logged: 13:43:05

Invalid host: 10.0.1.10:47365
```

After removing the integration and installing it again the host is discovered correctly.

I am using docker:
## System Health

version | core-2021.4.6
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
virtualenv | false
python_version | 3.8.7
os_name | Linux
os_version | 4.4.59+
arch | x86_64
timezone | UTC

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4664
Installed Version | 1.12.3
Stage | running
Available Repositories | 777
Installed Repositories | 17

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Lovelace</summary>

dashboards | 14
-- | --
resources | 7
views | 34
mode | storage

</details>

**Comment by B5r1oJ0A9G** [comment]
Hi @Ivanverdonck and @alexludwigklein,

Thanks for filing and pointing out this issue!

In the current implementation the Teufel host is validated during configuation/startup. If the host does not reply within 3 seconds or is not considered as a valid host, the setup fails.

https://github.com/B5r1oJ0A9G/teufel_raumfeld/blob/abf1da1eaa6a330e9bbf7332ad0677a351f46030/custom_components/teufel_raumfeld/__init__.py#L169-L172

I think it would be better, if it only fails during configuration and pauses the setup during startup while polling for availability.

Can you confirm that it works as before, when forcing the validation from above to succeed?

**Comment by alexludwigklein** [comment]
Hi Marc,

your proposal seem valid, but unfortunately I don't understand what I should confirm and/or test. I just did another test and restarted the server while the teufel device responded to 'http://<device ip>:47365/getZones' and the integration was sucessfully started.

Best,
Alexander

**Comment by B5r1oJ0A9G** [comment]
Thanks for the feedback @alexludwigklein!
Best,
Marc

**Comment by balk77** [comment]
is there a way to wake up a device so it gets properly detected? `if host_is_not_valid --> wake up, wait x seconds, poll again`.

**Comment by B5r1oJ0A9G** [comment]
> is there a way to wake up a device so it gets properly detected?

A Raumfeld device configured as host cannot be switched off and will always be on to receive commands. Devices controlled by a host may turn to stand-by or be disabled. Since these devices, resp. speakers are controlled by the host, this does not impact their manageability. The power status of speakers can be managed via `teufel_raumfeld.set_power_state`. See: https://github.com/B5r1oJ0A9G/teufel_raumfeld/wiki#services

The issue here is rather that the configured Raumfeld host is not running (e.g. unplugged), not reachable or not properly setup as a Host on the device side.

**Comment by balk77** [comment]
> > is there a way to wake up a device so it gets properly detected?
> 
> A Raumfeld device configured as host cannot be switched off and will always be on to receive commands. Devices controlled by a host may turn to stand-by or be disabled. Since these devices, resp. speakers are controlled by the host, this does not impact their manageability. The power status of speakers can be managed via `teufel_raumfeld.set_power_state`. See: https://github.com/B5r1oJ0A9G/teufel_raumfeld/wiki#services
> 
> The issue here is rather that the configured Raumfeld host is not running (e.g. unplugged), not reachable or not properly setup as a Host on the device side.

That is great news!

I have a single Raumfeld unit running (Connector 2) that goes asleep after x minutes of inactivity. It wakes when I start my favorite streaming service. I am experiencing exactly what is described in the OP. My thinking is to set the connector to `on` when restarting Home Assistant. The Teufel integration should then be able to find the Connector.
```
alias: 'Speakers: Raumfeld on at reboot'
description: ''
trigger:
  - platform: homeassistant
    event: shutdown
condition: []
action:
  - service: teufel_raumfeld.set_power_state
    data:
      entity_id: sensor.room_woonkamer_powerstate
      power_state: 'on'
mode: single
```
Just tested. Connector pops "on". But still the "Invalid Host" error 👎

**Comment by B5r1oJ0A9G** [comment]
@Ivanverdonck ,

I created a branch [dev-grace-time-host-setup](https://github.com/B5r1oJ0A9G/teufel_raumfeld/tree/dev-grace-time-host-setup). In the commit 8973495 I implemented a grace time about 30 seconds to wait for the configured Raumfeld host to become ready. Can you please test whether this resolves your issue and report back?

**Comment by B5r1oJ0A9G** [comment]
@balk77 ,

> Just tested. Connector pops "on". But still the "Invalid Host" error -1

Well, I have to admit that I cannot speak for the various possible Raumfeld setups. My setup is a One M as host and multiple Teufel S connected to it. This is the setup `teufel_raumfeld` was developed around.

The Spotify issue #4 showed me a new and unexpected aspect already. There it was due to the fact that I am using Tidal and not Spotify.

Concernign the Connector I'd have expectd that whatever status the device claims to have, that it would still be available for requests by `teufel_raumfeld`. However, It could be that the behavior having a single Connector is different. 

Could you perhaps test whether `teufel_raumfeld` is working after reboot, when having the validatoin removed - see https://github.com/B5r1oJ0A9G/teufel_raumfeld/issues/8#issuecomment-835539614?

**Comment by balk77** [comment]
> Could you perhaps test whether `teufel_raumfeld` is working after reboot, when having the validatoin removed - see [#8 (comment)](https://github.com/B5r1oJ0A9G/teufel_raumfeld/issues/8#issuecomment-835539614)?
I have commented these 4 lines and tried with the Connector in `eco` mode (without my pre-shutdown automation) and in `on` mode. Same result:

```
2021-05-20 20:13:54 INFO (MainThread) [homeassistant.setup] Setting up teufel_raumfeld 
2021-05-20 20:13:54 WARNING (MainThread) [custom_components.teufel_raumfeld copy] You are using teufel_raumfeld, which is still in alpha phase and therefore subject to change. This includes, among other things, the addition, redesign or removal of functionality. 
2021-05-20 20:13:54 INFO (MainThread) [homeassistant.setup] Setup of domain teufe_raumfeld took 0.0 seconds 
2021-05-20 20:14:01 ERROR (MainThread) [custom_components.teufel_raumfeld copy] Invalid host: 192.168.1.14:47365 
2021-05-20 20:14:07 ERROR (MainThread) [homeassistant.helpers.integration_platform] Unexpected error importing teufel_raumfeld/logbook.py 
ModuleNotFoundError: No module named 'custom_components.teufel_raumfeld copy.logbook' 
2021-05-20 20:14:07 ERROR (MainThread) [homeassistant.helpers.integration_platform] Unexpected error importing teufel_raumfeld/system_health.py 
ModuleNotFoundError: No module named 'custom_components.teufel_raumfeld copy.system_health' 
2021-05-20 20:14:07 ERROR (MainThread) [homeassistant.helpers.integration_platform] Unexpected error importing teufel_raumfeld/group.py 
ModuleNotFoundError: No module named 'custom_components.teufel_raumfeld copy.group' 
```
Deleting the integration, and re-adding it finds the Connector without problems.

**Comment by B5r1oJ0A9G** [comment]
Thanks for the feedback @balk77!
Could you then please also give it a try with the grace time mod mentioned in https://github.com/B5r1oJ0A9G/teufel_raumfeld/issues/8#issuecomment-844435997?

**Comment by balk77** [comment]
> Thanks for the feedback @balk77!
> Could you then please also give it a try with the grace time mod mentioned in [#8 (comment)](https://github.com/B5r1oJ0A9G/teufel_raumfeld/issues/8#issuecomment-844435997)?

also works 👍

**Comment by Ivanverdonck** [comment]
@B5r1oJ0A9G : I also tested "dev-grace-time-host-setup" , seems to work OK.

Thanks!

**Comment by B5r1oJ0A9G** [comment]
Thanks folks! I just merged the changes to the master branch.

**Comment by alexludwigklein** [comment]
That was fast, just my 50 cents: I have been testing your addition as well without any problems and avoiding any 'invalid host' problems

**Comment by B5r1oJ0A9G** [comment]
Thanks for the feedback @alexludwigklein! Glad we were able to find a quick solution.

Best,
Marc
